### ISSUE TITLE
Website For LTCIM

### ISSUE THREAD

**Issue by maektwain** [muellners/ltcim#1]
We use a static site generator for the website , Jekyll with a custom theme.

**Comment by livingrock7** [comment]
Here is the link of the work so far, I will help with the content.
http://ltcim.muellners.org/index

**Comment by livingrock7** [comment]
Some inputs from @maektwain 

1. We need to clean up the dir
2. Removing other non-essential. Moving all html pages to , dynamic page s

**Comment by maektwain** [comment]
#4 #8 #5 #6
