### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by maektwain** [muellners/ltcim#4]

**Comment by livingrock7** [comment]
http://ltcim.muellners.org/index

once content is updated I will mark this DONE

**Comment by maektwain** [comment]
@livingrock7 @tacitonic Were you able to get this done as suggested by @livingrock7 in the other issue.?

**Comment by tacitonic** [comment]
The site is down to html skeleton after latest commit it seems @maektwain @livingrock7

**Comment by maektwain** [comment]
@tacitonic Any update? should we be able to close this week?

**Comment by tacitonic** [comment]
Are there any changes other than content remaining? If not it can be closed by this week @maektwain

**Comment by maektwain** [comment]
Hey @tacitonic Looks like we agreed to change the important layout structure and redefine new pages also, If you could look into that.

**Comment by tacitonic** [comment]
Mark issue as done @maektwain ? I have added another issue for content updation.
